# Generated by Django 5.1.1 on 2024-09-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['nombre'],
            },
        ),
    ]
